### ISSUE TITLE
[feature] 마이페이지 수정 UI

### ISSUE THREAD

**Issue by MingyuChoi1** [E-5-KAIST-Team04/frontend#44]
### 📌 구현 기능

- 커뮤니티 페이지 수정

### 🛠 작업 내용

- [x] 보유 기술 선택할 때, 3개가 선택되면 자동으로 창을 닫히도록 설정
- [x] 보유 기술 선택할 때, "기타"를 눌러서 직접 기술을 입력할 때, 3개 이상의 보유 기술이 들어가게 되는 점 수정

### 💬 기타 사항

-

**Comment by aqua-universalis** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-07-22T13:37:12
          
          
            * 메일 제목 : 
Re: [E-5-KAIST-Team04/frontend] [feature] 마이페이지 수정 UI (Issue #44)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by aqua-universalis** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-07-22T13:47:21
          
          
            * 메일 제목 : 
Re: [E-5-KAIST-Team04/frontend] [feature] 마이페이지 수정 UI (Issue #44)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by aqua-universalis** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-07-22T13:53:44
          
          
            * 메일 제목 : 
Re: [E-5-KAIST-Team04/frontend] [feature] 마이페이지 수정 UI (Issue #44)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
